### ISSUE TITLE
Importing a save state results with an error

### ISSUE THREAD

**Issue by BloodRaynare** [beardypig/ghidra-emotionengine#62]
Everytime I tried to import a save states, this happens:

```
java.lang.NullPointerException
	at PCSX2SaveStateImporter.getBuffer(PCSX2SaveStateImporter.java:51)
	at PCSX2SaveStateImporter.loadMainMemory(PCSX2SaveStateImporter.java:59)
	at PCSX2SaveStateImporter.run(PCSX2SaveStateImporter.java:36)
	at ghidra.app.script.GhidraScript.executeNormal(GhidraScript.java:379)
	at ghidra.app.script.GhidraScript.doExecute(GhidraScript.java:234)
	at ghidra.app.script.GhidraScript.execute(GhidraScript.java:212)
	at ghidra.app.plugin.core.script.RunScriptTask.run(RunScriptTask.java:47)
	at ghidra.util.task.Task.monitoredRun(Task.java:124)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:104)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

---------------------------------------------------
Build Date: 2021-Mar-25 1203 EDT
Ghidra Version: 9.2.3
Java Home: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot
JVM Version: AdoptOpenJDK 11.0.11
OS: Windows 8.1 6.3 amd64
Workstation: Girumoa


```

**Comment by BloodRaynare** [comment]
Nevermind, turns out, I have to load the zipped save states (p2s)

**Comment by astrelsky** [comment]
> Nevermind, turns out, I have to load the zipped save states (p2s)

Does pcsx2 give a format option now when creating a save state?

**Comment by BloodRaynare** [comment]
> 
> Does pcsx2 give a format option now when creating a save state?

No, It's still saves to a gzipped (or zipped) format when you create one. It's just, looks like I attempted to load the eeMemory.bin directly from the unzipped save state files (which I've done on my own by using 7-zip).

**Comment by astrelsky** [comment]
> > 
> > Does pcsx2 give a format option now when creating a save state?
> 
> No, It's still saves to a gzipped (or zipped) format when you create one. It's just, looks like I attempted to load the eeMemory.bin directly from the unzipped save state files (which I've done on my own by using 7-zip).

Ok thank you. Just wanted to be sure.
